# Generated by Django 2.1.2 on 2018-10-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYSCHOOL', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblstudent',
            options={'managed': True},
        ),
    ]
