# Generated by Django 2.1.2 on 2018-10-23 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MYSCHOOL', '0003_auto_20181023_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudent',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
