# Generated by Django 2.1.2 on 2018-10-23 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYSCHOOL', '0004_auto_20181023_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudent',
            name='create_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
