# Generated by Django 2.1.2 on 2018-10-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYSCHOOL', '0005_auto_20181023_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblstudent',
            options={'managed': False},
        ),
    ]
