# Generated by Django 2.1.2 on 2018-10-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYSCHOOL', '0007_auto_20181023_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblstudent',
            options={},
        ),
        migrations.AlterModelTable(
            name='tblstudent',
            table=None,
        ),
    ]
